project: lora-cutoff

model_name_or_path: meta-llama/Llama-2-7b-hf

################################################################################
# TrainingArguments parameters
################################################################################

# Number of GPUs to use
num_processes: 8

# Output directory where the model predictions and checkpoints will be stored
output_dir: ./results

# Number of training epochs
num_train_epochs: 1

# Enable fp16/bf16 training (set bf16 to True with an A100)
fp16: True
bf16: False

# Batch size per GPU for training
per_device_train_batch_size: 4

# Batch size per GPU for evaluation
per_device_eval_batch_size: 4

# Number of update steps to accumulate the gradients for
gradient_accumulation_steps: 1

# Enable gradient checkpointing
gradient_checkpointing: True

# Maximum gradient normal (gradient clipping)
max_grad_norm: 0.3

# Initial learning rate (AdamW optimizer)
learning_rate: 3e-5

# Weight decay to apply to all layers except bias/LayerNorm weights
weight_decay: 0.001

# Optimizer to use
optim: paged_adamw_32bit

# Learning rate schedule
lr_scheduler_type: cosine

# Number of training steps (overrides num_train_epochs)
max_steps: -1

# Ratio of steps for a linear warmup (from 0 to learning rate)
warmup_ratio: 0.03

# Group sequences into batches with same length
# Saves memory and speeds up training considerably
group_by_length: True

# Save checkpoint every X updates steps
save_steps: .1

# Log every X updates steps
logging_steps: .1

gradient_accumulation_steps: 4

################################################################################
# DeepSpeed parameters
################################################################################

# Whether to use DeepSpeed
enable_deepspeed: False

stage: 3

offload: False

################################################################################
# LoraConfig parameters
################################################################################

# Whether to use LoRA
enable_lora: True

# LoRA attention dimension
lora_r: 8

# Alpha parameter for LoRA scaling
lora_alpha: 16

# Dropout probability for LoRA layers
lora_dropout: 0.05

################################################################################
# BitsAndBytesConfig parameters
################################################################################

# Activate 8-bit precision base model loading
load_in_8bit: False

# Activate 4-bit precision base model loading
load_in_4bit: False

# Compute dtype for 4-bit base models
bnb_4bit_compute_dtype: float16

# Quantization type (fp4 or nf4)
bnb_4bit_quant_type: nf4

# Activate nested quantization for 4-bit base models (double quantization)
use_nested_quant: True

################################################################################
# SFT parameters
################################################################################

# Maximum sequence length to use
max_seq_length: 2048

# Pack multiple short examples in the same input sequence to increase efficiency
packing: False